# Generated by Django 5.1.6 on 2025-02-22 04:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ABDR', 'Abductors'), ('ADDR', 'Adductors'), ('ABS', 'Abs'), ('BACK', 'Back'), ('BCPS', 'Biceps'), ('CLVS', 'Calves'), ('CHST', 'Chest'), ('FARM', 'Forearms'), ('GLTS', 'Glutes'), ('HMSTR', 'Hamstrings'), ('LBACK', 'Lower Back'), ('NCK', 'Neck'), ('QDCPS', 'Quadriceps'), ('SHDR', 'Shoulders'), ('TRPS', 'Trapezius'), ('TRCPS', 'Triceps')], max_length=81, null=True),
        ),
    ]
