# Generated by Django 5.1.6 on 2025-02-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment_guide_created_at_guide_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(to='api.equipment'),
        ),
    ]
