# Generated by Django 5.1.6 on 2025-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_equipment_image_url_exercise_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vestibulum tellus sed maximus. Vestibulum felis diam, auctor nec congue ut, vehicula vel turpis. Integer convallis porttitor ante. Etiam dignissim, dui in pharetra interdum, magna leo sagittis felis, eu imperdiet metus neque nec sem. Donec nec leo quis turpis rutrum maximus. Quisque at neque est. Ut ultricies gravida diam non tincidunt. Proin tempus dolor urna, ac fringilla enim vehicula eget. Donec imperdiet, odio sit amet porttitor tempor, nibh est rutrum dui, ac cursus purus augue a enim. Quisque mattis erat sed ultricies tempus. '),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vestibulum tellus sed maximus. Vestibulum felis diam, auctor nec congue ut, vehicula vel turpis. Integer convallis porttitor ante. Etiam dignissim, dui in pharetra interdum, magna leo sagittis felis, eu imperdiet metus neque nec sem. Donec nec leo quis turpis rutrum maximus. Quisque at neque est. Ut ultricies gravida diam non tincidunt. Proin tempus dolor urna, ac fringilla enim vehicula eget. Donec imperdiet, odio sit amet porttitor tempor, nibh est rutrum dui, ac cursus purus augue a enim. Quisque mattis erat sed ultricies tempus. '),
        ),
    ]
