# Generated by Django 5.1.6 on 2025-02-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_exercise_instructions_alter_guide_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='api.equipment'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
